import http from "node:http";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import morgan from "morgan";
import rateLimit from "express-rate-limit";
import { connectDB } from "./db.js";
import { config } from "./config.js";
import { initSocket } from "./services/socket.js";
import authRoutes from "./routes/auth.js";
import workflowRoutes from "./routes/workflows.js";
import approvalRoutes from "./routes/approvals.js";
import analyticsRoutes from "./routes/analytics.js";
import settingsRoutes from "./routes/settings.js";
import memoryRoutes from "./routes/memory.js";
import agentProxyRoutes from "./routes/agentProxy.js";
import riskRoutes from "./routes/risk.js";

const app=express();
app.set("trust proxy",1);
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:config.clientUrl,credentials:true}));
app.use(express.json({limit:"1mb"}));
app.use(cookieParser());
app.use(morgan(config.nodeEnv==="production"?"combined":"dev"));
app.use("/api/auth",rateLimit({windowMs:15*60*1000,max:100,standardHeaders:true,legacyHeaders:false}),authRoutes);
app.use("/api",rateLimit({windowMs:60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
app.get("/api/health",(_,res)=>res.json({status:"ok",service:"agentflow-platform",time:new Date().toISOString()}));
app.use("/api/workflow",workflowRoutes);
app.use("/api/approval",approvalRoutes);
app.use("/api/analytics",analyticsRoutes);
app.use("/api/settings",settingsRoutes);
app.use("/api/memory",memoryRoutes);
app.use("/api/agent",agentProxyRoutes);
app.use("/api/risk",riskRoutes);
app.use((req,res)=>res.status(404).json({message:"Route not found"}));
app.use((err,req,res,next)=>{ console.error(err); res.status(err.status||500).json({message:config.nodeEnv==="production"?"Internal server error":err.message}); });

const server=http.createServer(app);
initSocket(server);
connectDB().then(()=>server.listen(config.port,()=>console.log(`AgentFlow API listening on ${config.port}`))).catch(err=>{console.error("Startup failed",err);process.exit(1)});
